[users.employee1]
password = "pass123"
role = "employee"

[users.employee2]
password = "pass456"
role = "employee"

[users.admin]
password = "admin123"
role = "admin"

[users]
employee1 = { password = "pass123", role = "employee" }
employee2 = { password = "pass456", role = "employee" }
admin     = { password = "admin123", role = "admin" }
